### PR TITLE
At events

### PR DESCRIPTION
**Pull request by AudreyThomasson**
# Description
1- Add the events section to the dashboard. The add events + and the delete X are functional. Weather and edit are separate issue tickets.
2- Added images of wireframe to our readme file

## Type of change
-[x] New feature (non-breaking change which adds functionality)

# Testing Instructions
See if event list for Active User (if info is already in the database) is rendered when the dashboard appears. Try to add an event with the plus sign. Try to delete an event.

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my feature works

### CODE REVIEW

**Comment by ste163** [comment]
In my Jump start they mentioned the <br> tag is evil, and that all formatting should be done in CSS. 
Once these are removed, it's perfect!
- Remove ```<br> ``` tags on EventHTML.js
- Remove ``` <br> ``` tag on EventForm.js

**Review by ste163 — APPROVED** [review]
Looks awesome!

**Review by tristan0508 — APPROVED** [review]
Looks great!

**Review by HanakoH — APPROVED** [review]
Works for me!

**Pull request merged**
