### PR TITLE
fixed logout doubling up

### PR DESCRIPTION
**Pull request by terraroush**
# Description

- nutshell was being called on registerForm to kickoff the happenings, but it was called without an argument. that is now fixed and the correct welcome messages render with their owner

- logout button appears when there is an activeUser

- fixed logout doubling up bug. 

- also added divs for styling purposes around welcome greetings and logout button

Fixes # (logout button doubling when new user registers)
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# Testing Instructions
Begin with clear sessionStorage. (1)Login as return user (2)logout (3)without a refresh, register a new user (4) confirm there is one logout button (5) make sure the right message is displayed for the current activeUser
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ste163** [comment]
We got a bug! The issue is with WelcomeUser.js only rendering once, on page load. The welcome user text needs to live inside of a function. Otherwise: 
- when a user logins in
- then logs out
- then a user registers (ALL WITHOUT A PAGE REFRESH)
- the first user to login is shown on the welcome screen.

**Comment by terraroush** [comment]
> We got a bug! The issue is with WelcomeUser.js only rendering once, on page load. The welcome user text needs to live inside of a function. Otherwise:
> 
> * when a user logins in
> * then logs out
> * then a user registers (ALL WITHOUT A PAGE REFRESH)
> * the first user to login is shown on the welcome screen.

hmmm. did you refetch and git pull?

**Comment by HanakoH** [comment]
I can't seem to find the divs you put into the dashboard header.
I did a new fetch request but maybe I didn't fetch correctly?

**Review by ste163 — APPROVED** [review]
This ROCKS!

**Review by HanakoH — COMMENTED** [review]
Looks fantastic!

**Review by HanakoH — APPROVED** [review]
Approooved

**Comment by terraroush** [comment]
> I can't seem to find the divs you put into the dashboard header.
> I did a new fetch request but maybe I didn't fetch correctly?

Ah yes. They're in the JS(WelcomeUser.js ln 12, 15, 27 and LogoutComponent.js ln 29). I've left them without classes for you.

**Pull request merged**
