### PR TITLE
Tr validations

### PR DESCRIPTION
**Pull request by terraroush**
# Description

- added maximum character requirement for zip code field

- hid dashboard on page load, brought it back after authentication

- validated for zip code with function

- validated email with function

- provided alerts when other input is required

- sessionStorage conditional decides whether to display login/register or dashboard 

- added welcome message to dashboard for either activeUser or new user

Fixes # (possibility of bad zip code)
## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
Max character on zip code field prevents incorrect zip code;
function to assure the input is numerical;
- [x] New feature (non-breaking change which adds functionality)
dashboard is now hidden on page load, and reappears after authorization;
Email is now validated.

# Testing Instructions

- Test zip code requirements in registration 

- test reappearance by login or registration click

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by ste163** [comment]
This looks AMAZING! And the comments are awesome! But I just realized something functionality-wise that I think will be an easy fix.

After we log in once, and refresh the page, we're taken back to the login screen. However, in session storage, we're still logged in. There needs to be a check to say, "If there is an activeUser in sessionStorage, always show the dashboard. Else, if there is not an activeUser in sessionStorage, show the login page."

**Comment by terraroush** [comment]
> This looks AMAZING! And the comments are awesome! But I just realized something functionality-wise that I think will be an easy fix.
> 
> After we log in once, and refresh the page, we're taken back to the login screen. However, in session storage, we're still logged in. There needs to be a check to say, "If there is an activeUser in sessionStorage, always show the dashboard. Else, if there is not an activeUser in sessionStorage, show the login page."

Indeed! I've included the conditional.

**Review by tristan0508 — APPROVED** [review]
Looks great!! Killing it!

**Review by ste163 — APPROVED** [review]
The different sign-in messages for first time and returning users is genius!

**Pull request merged**
