### PR TITLE
Tw showing friends

### PR DESCRIPTION
**Pull request by tristan0508**
# Description

Events and News now show up for your FRIENDS!!! =]

Closed last PR since I made this one

But added the ability to alert you if a user does not exist.

Fixes # (issue)
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
# Testing Instructions
Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests
# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by terraroush — APPROVED** [review]
👍

**Comment by ste163** [comment]
Always gotta find some bugs 😉 
-  when adding a friend, the posts and events do not update (I think it just needs a dispatch event for when the friend is added to re-render)
- when activeUsers try to add themselves to their friends list, the alert message says the friend wasn't found, instead of saying that you can't add yourself.

**Comment by HanakoH** [comment]
I am having trouble clicking to add Events now. Anyone with a similar problem?

**Review by ste163 — APPROVED** [review]
Looks great!

**Pull request merged**
